name: Deploy latest repo code as mlproject on databricks
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Export MLFlow Tracking URI
        # export MLFLOW_TRACKING_URI=databricks
        run: export MLFLOW_TRACKING_URI=databricks
      - name : Install Dependencies
        run : python --version
              pip install databricks-cli
              pip install mlflow
      - name: Authenticate To Databricks Workspace
        run: echo ${{ secrets.AZURE_DATABRICKS_TOKEN }} > token-file
             databricks configure --host ${{ secrets.AZURE_DATABRICKS_HOST }} --token-file token-file
             rm -f token-file
